= arangodb-sample
:toc: auto

This project uses Quarkus, the Supersonic Subatomic Java Framework.

If you want to learn more about Quarkus, please visit its website: https://quarkus.io/.

== About ArangoDB

ArangoDB is a multi-model database that supports three data models: key/value, document, and graph, using a unified query language called AQL (Arango Query Language).
This flexibility makes it an excellent choice for projects that require relational data, document storage, or graph processing, without the need for separate databases.

Some features of ArangoDB include:
* Native multi-model support for graph, document, and key/value data.
* AQL (Arango Query Language) for powerful and flexible querying.
* Horizontal scaling and clustering capabilities.
* Built-in support for ACID transactions.
* Easy integration with programming languages, including Java.

To learn more about ArangoDB, visit the official website: https://www.arangodb.com/.

== Running ArangoDB

To execute an instance of ArangoDB locally using Docker, you can use the following command:

[source,shell]
----
docker run -e ARANGO_NO_AUTH=1 -d --name arangodb-instance -p 8529:8529 -d arangodb/arangodb
----


== Running the application in dev mode

You can run your application in dev mode that enables live coding using:

[source,shell]
----
./mvnw compile quarkus:dev
----

[NOTE]
====
Quarkus now ships with a Dev UI, which is available in dev mode only at http://localhost:8080/q/dev/.
====

== Packaging and running the application

The application can be packaged using:

[source,shell]
----
./mvnw package
----

It produces the `quarkus-run.jar` file in the `target/quarkus-app/` directory.
Be aware that it’s not an _über-jar_ as the dependencies are copied into the `target/quarkus-app/lib/` directory.

The application is now runnable using:

[source,shell]
----
java -jar target/quarkus-app/quarkus-run.jar
----

If you want to build an _über-jar_, execute the following command:

[source,shell]
----
./mvnw package -Dquarkus.package.jar.type=uber-jar
----

The application, packaged as an _über-jar_, is now runnable using:

[source,shell]
----
java -jar target/*-runner.jar
----

== Creating a native executable

You can create a native executable using:

[source,shell]
----
./mvnw package -Dnative
----

Or, if you don't have GraalVM installed, you can run the native executable build in a container using:

[source,shell]
----
./mvnw package -Dnative -Dquarkus.native.container-build=true
----

You can then execute your native executable with:

[source,shell]
----
./target/arangodb-sample-1.0.0-SNAPSHOT-runner
----

If you want to learn more about building native executables, please consult https://quarkus.io/guides/maven-tooling.

== Related Guides

* REST (https://quarkus.io/guides/rest): A Jakarta REST implementation utilizing build time processing and Vert.x.
This extension is not compatible with the `quarkus-resteasy` extension, or any of the extensions that depend on it.

== Provided Code

=== REST

Easily start your REST Web Services.

[Related guide section...](https://quarkus.io/guides/getting-started-reactive#reactive-jax-rs-resources)
